apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-test
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: "/mnt/data/mysql/test"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-test
  namespace: test
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
