apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-mysql-prod
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath: # Bu local storage örneği, external storage kullanabilirsin.
    path: "/mnt/data/mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-mysql-prod
  namespace: production # production namespace için ayrıca bir pvc tanımlayabilirsin
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
