apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysqlpv
  labels:
    app: mysql
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /nfsdata
    server: 10.255.255.10
