apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: junior-prod-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list"]

# Junior grubu prod ortamında bütün kaynakları görüntüleyebilir.
