apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: test
  name: junior-test-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

# Junior grubu test ortamında bütün kaynaklara erişim sağlayabilir.
