apiVersion: jaegertracing.io/v1
kind: Jaeger
metadata:
  name: linkerd-jaeger
  namespace: linkerd
spec:
  strategy: allInOne
  allInOne:
    options:
      log-level: debug
  ingress:
    enabled: true
  storage:
    type: memory

