apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-senior-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list"]

# Senior grubu cluster ortamında bütün kaynakları görüntüleyebilir.
