apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: production
  name: senior-prod-role
rules:
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["*"]

# Senior grubu prod ortamında bütün kaynaklara erişim sağlayabilir.
